/**
 * Sree Krushna Marriage OS — Customary Family Obligations Dataset
 * Standard: STD-FAMILY-OBLIGATION-001 | Ruling: AC-DEC-2026-061 / AC-DEC-2026-062
 * 
 * Auto-generated by scripts/compile-obligations.cjs. DO NOT EDIT DIRECTLY.
 */

window.FAMILY_OBLIGATIONS_DATA = {
  "meta": {
    "title": "Sree Krushna Marriage OS — Customary Family Obligations Register",
    "version": "1.0.0",
    "standard": "STD-FAMILY-OBLIGATION-001",
    "governance_ref": "AC-DEC-2026-061 & AC-DEC-2026-062",
    "updated_at": "2026-09-26T19:09:44.938Z"
  },
  "stats": {
    "total": 0,
    "by_direction": {
      "groom_to_bride": 0,
      "bride_to_groom": 0,
      "joint": 0,
      "external": 0
    },
    "by_lifecycle": {
      "Identified": 0,
      "Agreed": 0,
      "Procuring": 0,
      "Staged": 0,
      "Handed_Over": 0,
      "Waived": 0
    },
    "by_spec_status": {
      "Fully_Specified": 0,
      "TBD_Family_Choice": 0,
      "Source_Unclear": 0,
      "Source_Redacted": 0,
      "Pending_Family_Confirmation": 0
    },
    "by_epistemic_tier": {
      "SACRED_CORE": 0,
      "PROTOCOL_SPECIFIED": 0,
      "UNCERTAIN_EXPLORATORY": 0
    },
    "unresolved_count": 0
  },
  "obligations": []
};
