#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Multi-Sheet Excel Processor (DCE-001 / APS-001)
-----------------------------------------------
Certified by Architecture Council Review: 260914_arch_council_multisheet_excel_processing.
Provides robust multi-sheet Excel inspection, markdown conversion, schema validation,
and tabular consolidation with automatic Python environment self-discovery.
"""

import sys
import os
import shutil
import tempfile
import argparse
import json
from pathlib import Path

# --- Environment Self-Discovery ---
def find_python_environment():
    """Locate the nearest viable Python virtual environment with pandas and openpyxl."""
    candidates = [
        sys.executable,
        Path(__file__).resolve().parents[4] / "BMS" / "venv" / "Scripts" / "python.exe",
        Path(r"D:\GitHub_Repo\BMS\venv\Scripts\python.exe"),
        Path(r"D:\GitHub_Repo\Sree_Krushna\venv\Scripts\python.exe"),
    ]
    for cand in candidates:
        cand_path = Path(cand)
        if cand_path.exists() and cand_path.is_file():
            return str(cand_path)
    return sys.executable

def safe_open_path(file_path):
    """
    Guards against Windows Excel file-locking (EBUSY / PermissionError)
    by creating a temporary copy if direct reading encounters a lock.
    """
    target = Path(file_path).resolve()
    if not target.exists():
        raise FileNotFoundError(f"Source file not found: {target}")
    
    # Try opening for read access
    try:
        with open(target, 'rb') as f:
            f.read(1024)
        return str(target), None
    except (PermissionError, IOError):
        # File is locked by another process (e.g. MS Excel)
        temp_dir = tempfile.mkdtemp(prefix="excel_proc_")
        temp_copy = Path(temp_dir) / target.name
        shutil.copy2(target, temp_copy)
        return str(temp_copy), temp_dir

def detect_header_row(ws, max_scan_rows=10):
    """
    Scans first N rows of an openpyxl worksheet to determine the true header row,
    avoiding merged title blocks or decorative banners.
    """
    best_row_idx = 0
    max_non_empty = 0
    
    for row_idx, row in enumerate(ws.iter_rows(max_row=max_scan_rows, values_only=True)):
        non_empty = sum(1 for cell in row if cell is not None and str(cell).strip() != '')
        if non_empty > max_non_empty:
            max_non_empty = non_empty
            best_row_idx = row_idx
            
    return best_row_idx

def inspect_workbook(file_path):
    """Inspects sheet names, dimensions, column types, and formula presence."""
    import openpyxl
    
    safe_path, temp_dir = safe_open_path(file_path)
    try:
        wb = openpyxl.load_workbook(safe_path, read_only=True, data_only=False)
        report = {
            "workbook": os.path.basename(file_path),
            "file_size_kb": round(os.path.getsize(safe_path) / 1024, 2),
            "sheet_count": len(wb.sheetnames),
            "sheets": []
        }
        
        for name in wb.sheetnames:
            ws = wb[name]
            header_offset = detect_header_row(ws)
            
            # Sample headers
            headers = []
            for row in ws.iter_rows(min_row=header_offset + 1, max_row=header_offset + 1, values_only=True):
                headers = [str(c) if c is not None else f"Unnamed_{i}" for i, c in enumerate(row)]
                break
                
            report["sheets"].append({
                "name": name,
                "max_row": ws.max_row,
                "max_column": ws.max_column,
                "detected_header_row": header_offset + 1,
                "headers": headers[:15]  # first 15 headers
            })
            
        return report
    finally:
        if temp_dir and os.path.exists(temp_dir):
            shutil.rmtree(temp_dir, ignore_errors=True)

def convert_to_markdown(file_path, output_file=None, max_rows_per_sheet=100):
    """Converts each sheet into a clean Markdown table."""
    import pandas as pd
    
    safe_path, temp_dir = safe_open_path(file_path)
    markdown_chunks = []
    base_name = Path(file_path).stem
    
    markdown_chunks.append(f"# Workbook: {base_name}\n")
    markdown_chunks.append(f"> Auto-generated by `excel-multisheet-processor`\n")
    
    try:
        sheets = pd.read_excel(safe_path, sheet_name=None, dtype=str)
        for sheet_name, df in sheets.items():
            markdown_chunks.append(f"\n## Sheet: {sheet_name}\n")
            if df.empty:
                markdown_chunks.append("*[Empty Sheet]*\n")
                continue
                
            # Truncate if exceeds max rows to prevent LLM token explosion
            total_rows = len(df)
            if total_rows > max_rows_per_sheet:
                display_df = df.head(max_rows_per_sheet)
                markdown_chunks.append(f"*Displaying first {max_rows_per_sheet} of {total_rows} rows:*\n\n")
            else:
                display_df = df
                
            # Replace NaNs with empty string
            clean_df = display_df.fillna('')
            # Native zero-dependency markdown table formatting (eliminates tabulate requirement)
            headers = [str(c) for c in clean_df.columns]
            lines = []
            lines.append("| " + " | ".join(headers) + " |")
            lines.append("| " + " | ".join([":---"] * len(headers)) + " |")
            for _, row in clean_df.iterrows():
                row_vals = [str(val).replace("\n", " ").replace("|", "\\|") for val in row]
                lines.append("| " + " | ".join(row_vals) + " |")
            markdown_chunks.append("\n".join(lines))
            markdown_chunks.append("\n")
            
        full_md = "\n".join(markdown_chunks)
        
        if output_file:
            out_path = Path(output_file)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(full_md)
                
        return full_md
    finally:
        if temp_dir and os.path.exists(temp_dir):
            shutil.rmtree(temp_dir, ignore_errors=True)

def consolidate_sheets(file_path, output_file, sheets_to_merge=None):
    """
    Merges specified sheets (or all sheets) into a single unified table
    adding a '_source_sheet' identifier column.
    """
    import pandas as pd
    
    safe_path, temp_dir = safe_open_path(file_path)
    try:
        all_sheets = pd.read_excel(safe_path, sheet_name=None, dtype=str)
        frames = []
        
        for name, df in all_sheets.items():
            if sheets_to_merge and name not in sheets_to_merge:
                continue
            if df.empty:
                continue
            df_copy = df.copy()
            df_copy.insert(0, "_source_sheet", name)
            frames.append(df_copy)
            
        if not frames:
            raise ValueError("No matching or non-empty sheets found to consolidate.")
            
        consolidated = pd.concat(frames, ignore_index=True)
        
        out_path = Path(output_file)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        
        if out_path.suffix.lower() in ('.xlsx', '.xls'):
            with pd.ExcelWriter(out_path, engine='xlsxwriter') as writer:
                consolidated.to_excel(writer, sheet_name="Consolidated_Master", index=False)
        elif out_path.suffix.lower() == '.csv':
            consolidated.to_csv(out_path, index=False, encoding='utf-8')
        elif out_path.suffix.lower() == '.json':
            consolidated.to_json(out_path, orient='records', indent=2)
        else:
            raise ValueError(f"Unsupported output format: {out_path.suffix}")
            
        return {
            "status": "SUCCESS",
            "consolidated_rows": len(consolidated),
            "consolidated_columns": len(consolidated.columns),
            "output_file": str(out_path)
        }
    finally:
        if temp_dir and os.path.exists(temp_dir):
            shutil.rmtree(temp_dir, ignore_errors=True)

def validate_schema(file_path, required_columns):
    """Checks that every sheet (or specific sheet) contains required columns."""
    import pandas as pd
    
    safe_path, temp_dir = safe_open_path(file_path)
    try:
        sheets = pd.read_excel(safe_path, sheet_name=None, nrows=1, dtype=str)
        results = {}
        all_valid = True
        
        for sheet_name, df in sheets.items():
            sheet_cols = set(df.columns.astype(str))
            req_cols = set(required_columns)
            missing = req_cols - sheet_cols
            is_valid = len(missing) == 0
            if not is_valid:
                all_valid = False
            results[sheet_name] = {
                "valid": is_valid,
                "missing_columns": sorted(list(missing)),
                "present_columns": sorted(list(sheet_cols))
            }
            
        return {
            "all_valid": all_valid,
            "sheets": results
        }
    finally:
        if temp_dir and os.path.exists(temp_dir):
            shutil.rmtree(temp_dir, ignore_errors=True)

def main():
    parser = argparse.ArgumentParser(description="Multi-Sheet Excel Processor (DCE-001)")
    parser.add_argument("input_file", help="Path to target Excel workbook (.xlsx, .xls)")
    parser.add_argument("--inspect", action="store_true", help="Inspect sheet names, rows, and columns")
    parser.add_argument("--to-markdown", action="store_true", help="Convert all sheets to clean Markdown")
    parser.add_argument("--consolidate", action="store_true", help="Merge multiple sheets into a single file")
    parser.add_argument("--validate", nargs="+", help="Validate presence of required column headers")
    parser.add_argument("--sheets", nargs="+", help="Specific sheet names to target")
    parser.add_argument("--output", "-o", help="Output file path (.md, .xlsx, .csv, .json)")
    parser.add_argument("--max-rows", type=int, default=100, help="Max rows per sheet for markdown export")
    parser.add_argument("--json", action="store_true", help="Output results in JSON format")

    args = parser.parse_args()

    if not os.path.exists(args.input_file):
        print(json.dumps({"error": f"File not found: {args.input_file}"}) if args.json else f"Error: File not found: {args.input_file}")
        sys.exit(1)

    if args.inspect:
        res = inspect_workbook(args.input_file)
        if args.json:
            print(json.dumps(res, indent=2))
        else:
            print(f"\nWorkbook: {res['workbook']} ({res['file_size_kb']} KB)")
            print(f"Total Sheets: {res['sheet_count']}")
            print("-" * 60)
            for s in res["sheets"]:
                print(f" • [{s['name']}]: {s['max_row']} rows x {s['max_column']} cols (Header @ row {s['detected_header_row']})")
                print(f"   Headers: {', '.join(s['headers'][:6])} ...")
            print("-" * 60)

    elif args.to_markdown:
        md_text = convert_to_markdown(args.input_file, args.output, args.max_rows)
        if not args.output:
            print(md_text)
        else:
            print(f"[+] Markdown exported successfully to: {args.output}")

    elif args.consolidate:
        if not args.output:
            print("Error: --output path required for consolidation.")
            sys.exit(1)
        res = consolidate_sheets(args.input_file, args.output, args.sheets)
        print(json.dumps(res, indent=2) if args.json else f"[+] Consolidated {res['consolidated_rows']} rows into: {res['output_file']}")

    elif args.validate:
        res = validate_schema(args.input_file, args.validate)
        print(json.dumps(res, indent=2))
        if not res["all_valid"]:
            sys.exit(2)
    else:
        # Default action: inspect
        res = inspect_workbook(args.input_file)
        print(json.dumps(res, indent=2))

if __name__ == "__main__":
    main()
